name: Rebased
on:
  push:
    branches:
      - master
    tags:
      - 'rebased/*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: get build number
        id: get_version
        run: |
          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
            version="${GITHUB_REF_NAME##*/}"
          else
            version="$(cat build.txt)"
          fi
          echo "version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

  build:
    needs: get_version
    uses: ./.github/workflows/ide_build_and_upload.yml
    with:
      artifacts_dir: out/idea-ce/artifacts
      product: intellij_idea
      version: ${{ needs.get_version.outputs.version }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - get_version
      - build
    if: startsWith(github.ref, 'refs/tags/rebased/')
    steps:
      - uses: actions/download-artifact@v4.1.8

      - name: create appimage zsync file
        run: zsyncmake *.AppImage

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          title: ${{ needs.get_version.outputs.version }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          files: |
            *.tar.gz
            *.AppImage
            *.zsync
            *.exe
            *.dmg
            