name: Rebased
on:
  push:
    branches:
      - master
    tags:
      - 'rebased/*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  parse_tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse_tag.outputs.version }}
    steps:
      - name: Parse tag
        id: parse_tag
        run: echo "version=${GITHUB_REF_NAME##*/}" >> $GITHUB_OUTPUT

  build:
    needs: parse_tag
    uses: ./.github/workflows/ide_build_and_upload.yml
    with:
      artifacts_dir: out/idea-ce/artifacts
      product: intellij_idea
      version: ${{ needs.parse_tag.outputs.version }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - parse_tag
      - build
    if: startsWith(github.ref, 'refs/tags/rebased/')
    steps:
      - uses: actions/download-artifact@v4.1.8
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          title: ${{ needs.parse_tag.outputs.version }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          draft: true
          files: |
            *.tar.gz
            *.AppImage
            *.exe
            *.dmg
            